site_name: BifrostTools documentation
site_url: https://ita-solar.github.io/BifrostTools/

# Repository
repo_name: ita-solar/BifrostTools.jl
repo_url: https://github.com/ITA-Solar/BifrostTools.jl/
edit_uri: ""

nav:
    - BifrostTools: index.md
    - Installation: install.md
    - Example usage: usage.md
theme:
    name: 'material'