name = "BifrostTools"
uuid = "526b3974-5bd8-47e8-be8d-381be867b53b"
authors = ["eilifso <e.s.oyre@astro.uio.no>", "meudnaes <eliasudnes@hotmail.com>"]
version = "0.1.0"

[deps]
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

